### ISSUE TITLE
Warning ler_partes

### ISSUE THREAD

**Issue by conraddo** [jjesusfilho/tjsp#30]
Usar a função ler_partes gera uma tabela sem as informações dos patronos das partes e um warning informando que foram processadas mais colunas do que o esperado.

**Comment by jjesusfilho** [comment]
Eu atualizei a função.  Pode testar novamente?

**Comment by conraddo** [comment]
Acho que continua com o mesmo erro. 

![image](https://user-images.githubusercontent.com/42458490/121214340-6956be80-c855-11eb-9ee9-bf21a78b5773.png)

**Comment by jjesusfilho** [comment]
Mas esse é o resultado esperado. Você pode ignorar esse warning. Eu testei e está retornando a mesma tabela. As informações dos representantes estão lá. Eu não vou além na estruturação dos representantes porque geralmente vem resultados inesperados.
