### ISSUE TITLE
Versionamento 

### ISSUE THREAD

**Issue by ericlesaquiles** [jjesusfilho/tjsp#33]
Olá!
Comecei a ter problemas depois de uma atualização recente, e me veio a pergunta se você usa algum sistema de versionamento.

Usa? 

O pacote aparece para mim como "versão 2.0.0", mas, olhando no repositório, não achei fácil como me referir às versões anteriores.

Isso seria útil para tornar o projeto em que estou trabalhando mais estável.

**Comment by jjesusfilho** [comment]
@ericlesaquiles, lamento que isso tenha acontecido. Eu nem sempre gero novo  número quando atualizo o pacote. Não sei como você está usando, mas eu criei um novo conjunto de funções que contêm cd_processo no nome e são mais rápidas e mais seguras. No entanto, isso também gerou alguma confusão com os códigos antigos. Seja como for, você pode dar um fork na versão que está funcionando para você ou instalar a versão desejada com base no commit: https://github.com/jjesusfilho/tjsp/commits/main/
