### ISSUE TITLE
problemas com a funcao mni_consultar_processo 

### ISSUE THREAD

**Issue by rubensolv** [jjesusfilho/tjsp#36]
Estou verificando o uso do recurso mni_consultar_processo, porem tentei incluir usuario e senha de todas as formas possiveis para os campos 
' @param usuario Informar usuario ou variável de ambiente
#'     TJSPMNIUSUARIO
#' @param senha Informar senha ou variável de ambiente
#'     TJSPMNISENHA

E infezlimente so obtenho a resposta do xml:
><sucesso>false</sucesso><mensagem>CODIGO: 501 - MENSAGEM: Login/senha informados estão inválidos. 
</mensagem></ns4:consultarProcessoResposta></soap:Body></soap:Envelope>

Validei o usuario e senha no esaj (https://esaj.tjsp.jus.br/) e o login ocorre perfeitamente. 

Poderia me auxiliar com esse problema?

Desde ja agradeco.

**Comment by jjesusfilho** [comment]
Oi Ruben, essa função só pode ser chamada por quem tem acesso ao MNI. O TJSP tem de previamente credenciar a sua organização.
